---
myimage1: "../img/section/DensitySmall.png"
myimage2: "../img/section/Box1Small.png"
mytitle: "Work in progress"
output:
  html_document:
      template: template_story.html
      theme: "lumen"
      css: style.css
      toc: FALSE
      toc_float: TRUE
      toc_depth: 2
      number_sections: TRUE
      df_print: "paged"
      code_folding: "hide"
      includes: 
        after_body: footer.html
---

<br><br>
<div class="mycontent">
This page is still work in progress. Sorry for the inconvenience.




Work on the gender gap
data recovered here: https://stats.oecd.org/index.aspx?queryid=54751
and coming from the Employment database: http://www.oecd.org/employment/emp/onlineoecdemploymentdatabase.htm of OECD.org
The gender wage gap is defined as the difference between male and female median wages divided by the male median wages.

```{r}
data <- read.table("~/Downloads/GENDER_EMP_06062018110412742.csv", header=T, sep=",")

library(tidyverse)
tmp <- data %>%
  select(Country, TIME, Value) %>%
  filter(TIME %in% c(2000, 2005, 2010, 2015)) %>%
  arrange(Country) %>%
  filter(!is.na(Value))

write.table(tmp, "/Users/y.holtz/Dropbox/data_to_viz/Example_dataset/9_OneNumSevCatSubgroupOneObs.csv", sep=",", row.names=FALSE)

data <- read.table("/Users/y.holtz/Dropbox/data_to_viz/Example_dataset/9_OneNumSevCatSubgroupOneObs.csv", header=T, sep=",")
```



```{r, fig.width=8}
data

# Grouped
data %>%
  ggplot(aes(fill=as.factor(TIME), y=Value, x=Country)) + 
    geom_bar(position="dodge", stat="identity") +
    coord_flip()


```





</div>