---
myimage1: "../img/mistake/dual_axis.png"
pathSlug: "dual_axis"
mytitle: "The issue with dual axis"
output:
  html_document:
      template: template_caveat.html
      theme: "lumen"
      css: style.css
      toc: FALSE
      toc_float: TRUE
      toc_depth: 2
      number_section: FALSE
      df_print: "paged"
      code_folding: "hide"
      includes:
        after_body: footer.html

---

<br><br>
<div class="mycontent">


# Example
***
good example coming from [Planned-Parenthood](http://emschuch.github.io/Planned-Parenthood/) and from [Politifact](http://www.politifact.com/truth-o-meter/statements/2015/oct/01/jason-chaffetz/chart-shown-planned-parenthood-hearing-misleading-/), initially published on [aul.org](http://www.aul.org).


Data here
https://docs.google.com/spreadsheets/d/1vzkuzSi2S-JO0m0VolflzxaMN9wUfjw6Slek97_6L4s/edit#gid=0





```{r, fig.align='center', fig.height=6, fig.width=6, warning=FALSE, message=FALSE}
library(plotly)

ay <- list(
  tickfont = list(color = "red"),
  overlaying = "y",
  side = "right",
  title = "second y axis"
)
p <- plot_ly() %>%
  add_lines(x = ~1:3, y = ~10*(1:3), name = "slope of 10") %>%
  add_lines(x = ~2:4, y = ~1:3, name = "slope of 1", yaxis = "y2") %>%
  layout(
    title = "Double Y Axis", yaxis2 = ay,
    xaxis = list(title="x")
  )

# add slider control to plot
p <- p %>%
  layout(sliders = list(list(active = 3,
                             currentvalue = list(prefix = "Frequency: "),
                             steps = c(1:10))))
p
```

```{r}
x <- seq(0,10, length.out = 1000)

# create data
aval <- list()
for(step in 1:11){
  aval[[step]] <-list(visible = FALSE,
                      name = paste0('v = ', step),
                      x=x,
                      y=sin(step*x))
}
aval[3][[1]]$visible = TRUE



# create steps and plot all traces
steps <- list()
p <- plot_ly()
for (i in 1:11) {
  p <- add_lines(p,x=aval[i][[1]]$x,  y=aval[i][[1]]$y, visible = aval[i][[1]]$visible,
                 name = aval[i][[1]]$name, type = 'scatter', mode = 'lines', hoverinfo = 'name',
                 line=list(color='00CED1'), showlegend = FALSE)

  step <- list(args = list('visible', rep(FALSE, length(aval))),
               method = 'restyle')
  step$args[[2]][i] = TRUE
  steps[[i]] = step
}

# add slider control to plot
p <- p %>%
  layout(sliders = list(list(active = 3,
                             currentvalue = list(prefix = "Frequency: "),
                             steps = steps)))
p
```



find how to add a slider:
https://plot.ly/r/sliders/




</div>














